name: umpire-quiz
services:

  frontend:
    image: opleiding-harbor.bcverdouw.nl/wc/umpire_quiz_frontend:${FRONTEND_VERSION}
    pull_policy: always
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      USER_SERVICE_URL: "${USER_SERVICE_URL}"
      BACKEND_URL: "${BACKEND_URL}"
      IMPORTER_URL: "${IMPORTER_URL}"

  backend:
    image: opleiding-harbor.bcverdouw.nl/wc/umpire_quiz_questionservice:${BACKEND_VERSION}
    pull_policy: always
    ports:
      - "${BACKEND_PORT}:9080"
    environment:
      MYSQL_HOSTNAME: "backend-db"
      MYSQL_PORT: "3306"
      MYSQL_ROOT_PASSWORD: "${BACKEND_DB_PASSWORD}"
      MYSQL_DATABASE: "${BACKEND_DB_NAME}"
      FRONTEND_URL: "${FRONTEND_URL}"
      JWT_SHAREDKEY: "${JWT_SHAREDKEY}"
    depends_on:
      backend-db:
        condition: service_healthy

  backend-db:
    image: docker.io/mysql:${DB_VERSION}
    pull_policy: missing
    healthcheck:
      test: ["CMD", "mysqladmin ping -h 127.0.0.1 --user=root --password=$$MYSQL_ROOT_PASSWORD" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: "${BACKEND_DB_PASSWORD}"
      MYSQL_DATABASE: "${BACKEND_DB_NAME}"
    volumes:
      - "backend-db-data:/var/lib/mysql"

  # --- Importer service --- #
  importer-service:
    image: opleiding-harbor.bcverdouw.nl/wc/umpire_quiz_importerservice:${IMPORTER_SERVICE_VERSION}
    pull_policy: always
    ports:
      - "${IMPORTER_SERVICE_PORT}:9080"
    environment:
      MYSQL_HOSTNAME: "backend-db"
      MYSQL_PORT: "3306"
      MYSQL_ROOT_PASSWORD: "${BACKEND_DB_PASSWORD}"
      MYSQL_DATABASE: "${BACKEND_DB_NAME}"
      FRONTEND_URL: "${FRONTEND_URL}"
      JWT_SHAREDKEY: "${JWT_SHAREDKEY}"
    depends_on:
      backend-db:
        condition: service_healthy
      backend:
        condition: service_healthy
  # --- End Importer service --- #

  # --- User service --- #
 user-service:
   image: opleiding-harbor.bcverdouw.nl/wc/umpire_quiz_userservice:${USER_SERVICE_VERSION}
   pull_policy: always
   ports:
     - "${USER_SERVICE_PORT}:9080"
   environment:
     MYSQL_HOSTNAME: "user-service-db"
     MYSQL_PORT: "3306"
     MYSQL_ROOT_PASSWORD: "${USER_SERVICE_DB_PASSWORD}"
     MYSQL_DATABASE: "${USER_SERVICE_DB_NAME}"
     FRONTEND_URL: "${FRONTEND_URL}"
     JWT_SHAREDKEY: "${JWT_SHAREDKEY}"
   depends_on:
     - user-service-db

  user-service-db:
    image: docker.io/mysql:${DB_VERSION}
    pull_policy: missing
    healthcheck:
      test: ["CMD", "mysqladmin ping -h 127.0.0.1 --user=root --password=$$MYSQL_ROOT_PASSWORD" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: "${USER_SERVICE_DB_PASSWORD}"
      MYSQL_DATABASE: "${USER_SERVICE_DB_NAME}"
    volumes:
      - "user-service-db-data:/var/lib/mysql"
  # --- End User service --- #

volumes:
  backend-db-data:
  user-service-db-data:
